### ISSUE TITLE
Integrate with Strap

### ISSUE THREAD

**Issue by MikeMcQuaid** [benbalter/plister#2]
It would be cool to do something like this: https://github.com/mikemcquaid/strap/blob/78e162d5d239d1bfb5788d4dd9fb8bb7222fac13/bin/strap.sh#L277-L298

so users of Strap could have their OS X settings set/reset at a sensible point.

**Comment by benbalter** [comment]
@mikemcquaid since it's Ruby, what'd be the best way to install the Gem / execute it?

If `~/.osx.yml` exists, it'd be as simple as `bundle exec plister` to set things up.

**Comment by MikeMcQuaid** [comment]
@benbalter I guess probably `gem install --user plister; plister ~/.osx.yml` or similar (to avoid reinstalling if it's unnecessary)?

**Comment by MikeMcQuaid** [comment]
@benbalter I guess it'll need a new release too.
